export const weatherCodeMap: Record<number, { emoji: string; label: string }> = {
    0: { emoji: "☀️", label: "Clear sky" },
    1: { emoji: "🌤️", label: "Mainly clear" },
    2: { emoji: "⛅", label: "Partly cloudy" },
    3: { emoji: "☁️", label: "Overcast" },
    45: { emoji: "🌫️", label: "Fog" },
    48: { emoji: "🌫️", label: "Rime fog" },
    51: { emoji: "🌦️", label: "Light drizzle" },
    53: { emoji: "🌦️", label: "Moderate drizzle" },
    55: { emoji: "🌧️", label: "Dense drizzle" },
    56: { emoji: "🌧️❄️", label: "Light freezing drizzle" },
    57: { emoji: "🌧️❄️", label: "Dense freezing drizzle" },
    61: { emoji: "🌧️", label: "Slight rain" },
    63: { emoji: "🌧️", label: "Moderate rain" },
    65: { emoji: "🌧️", label: "Heavy rain" },
    66: { emoji: "🌧️❄️", label: "Light freezing rain" },
    67: { emoji: "🌧️❄️", label: "Heavy freezing rain" },
    71: { emoji: "🌨️", label: "Slight snow" },
    73: { emoji: "🌨️", label: "Moderate snow" },
    75: { emoji: "❄️", label: "Heavy snow" },
    77: { emoji: "❄️", label: "Snow grains" },
    80: { emoji: "🌦️", label: "Slight rain showers" },
    81: { emoji: "🌧️", label: "Moderate rain showers" },
    82: { emoji: "🌧️", label: "Violent rain showers" },
    85: { emoji: "🌨️", label: "Slight snow showers" },
    86: { emoji: "🌨️", label: "Heavy snow showers" },
    95: { emoji: "⛈️", label: "Thunderstorm" },
    96: { emoji: "⛈️❄️", label: "Thunderstorm with slight hail" },
    99: { emoji: "🌩️❄️", label: "Thunderstorm with heavy hail" },
  };
  